<% require "dotenv"; Dotenv.load(".env") %>

service: portfolio

image: onezerospace/portfolio

servers:
  web:
    - <%= ENV["SERVER_IP"] %>

proxy:
  ssl: false
  host: <%= ENV["PHX_HOST"] %>
  app_port: <%= ENV["APP_PORT"] %>

registry:
  server: ghcr.io
  username: <%= ENV["DOCKER_REGISTRY_USERNAME"] %>
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  remote: ssh://root@<%= ENV["SERVER_IP"] %>

env:
  clear:
    PORT: <%= ENV["APP_PORT"] %>
    MIX_ENV: prod
    PHX_HOST: <%= ENV["PHX_HOST"] %>
  secret:
    - SECRET_KEY_BASE
